// frontend-svelte/src/Player.svelte
<script>
  import { queue as store } from './store';
  import Youtube from './lib/youtube';
  import YoutubePlayer from './YoutubePlayer.svelte';

  let videoId;
  let lastVideo;

  const unsubscribe = store.subscribe(value => {
    if (value.length === 0) {
      videoId = null;
      return;
    }

    const [current] = value;
    videoId = current.id;

    lastVideo = value[value.length - 1];
  });

  const opts = {
    height: '100%',
    width: '100%',
    playerVars: {
      autoplay: 1,
      controls: 0,
      fs: 0,
      showinfo: 0,
    },
  };

  const onEnd = async () => {
    store.onEnd();

    if (!lastVideo) {
      return;
    }

    const results = await Youtube('', { relatedToVideoId: lastVideo.id, maxResults: 5 });
    store.addBatch(results);
  };
</script>

<style>
  .PlayerWrapper {
    grid-area: player;
    position: relative;
  }

  :global(.Player) {
    position: absolute;
    top: 0;
    left: 0;
  }
</style>

<div class="PlayerWrapper">
  <YoutubePlayer class="Player" {videoId} {opts} {onEnd} />
</div>

// frontend-react/src/components/Player/index.js
import React from 'react';
import styles from './Player.module.scss';
import YouTube from 'react-youtube';
import { useStateContext } from '../State';

function Video(props) {
  const { onVideoEnd, debug } = useStateContext();
  const { video } = props;

  if (!video) {
    return null;
  }

  const opts = {
    height: '100%',
    width: '100%',
    playerVars: {
      autoplay: 1,
      controls: debug ? 0 : 1,
      fs: 0,
      showinfo: 0,
    },
  };

  return <YouTube videoId={video.id} opts={opts} onEnd={e => onVideoEnd()} className={styles.Player} />;
}

export default function Player() {
  const { queue } = useStateContext();
  const [current] = queue;

  return (
    <div className={styles.PlayerWrapper}>
      <Video video={current} />
    </div>
  );
}
