// frontend-react/src/components/Header/index.js
import React from 'react';
import logo from './logo.png';
import styles from './Header.module.scss';

function Wrapper() {
  return (
    <div className={styles.Header}>
      <img src={logo} alt="MyntPlayer" />
      <div className={styles.Credit}>v4.0 by MyntLabs.com © {new Date().getFullYear()}</div>
    </div>
  );
}

export default Wrapper;

// frontend-svelte/src/Header.svelte
<style>
  .Credit {
    font-size: 0.8em;
    padding: 0 15px;
    color: #999;
  }

  .Header {
    grid-area: header;
    display: flex;
    align-items: center;
  }
</style>

<div class="Header">
  <img src="logo-full.png" alt="MyntPlayer" />
  <div class="Credit">v4.0 by MyntLabs.com © {new Date().getFullYear()}</div>
</div>
