// frontend-svelte/src/QR.svelte
<script>
  import QRCode from 'qrcode-generator';
  export let masterId;

  const addUrl = `${document.location.origin}/add/${masterId}`;

  const qr = QRCode(4, 'L');
  qr.addData(addUrl);
  qr.make();

  const data = qr.createDataURL();
</script>

<style>
  a {
    position: absolute;
    bottom: 0;
    right: 0;
  }

  img {
    width: 100px;
  }
</style>

<a href={addUrl} rel="noopener noreferrer" target="_blank">
  <img src={data} alt="Add Page" />
</a>

// frontend-react/src/components/QR/index.js
import React, { useState, useEffect } from 'react';
import QRCode from 'qrcode';

export default function QR(props) {
  const { masterId } = props;
  const [qr, setQr] = useState(null);
  const addUrl = `${document.location.origin}/add/${masterId}`;

  useEffect(
    _ => {
      QRCode.toDataURL(addUrl, {
        color: {
          light: '#000000ff',
          dark: '#ffffff',
        },
      }).then(url => {
        setQr(url);
      });
    },
    [addUrl]
  );

  if (!qr) {
    return null;
  }

  return (
    <a href={addUrl} rel="noopener noreferrer" target="_blank" className={props.className}>
      <img src={qr} alt="QR" style={{ width: 140 }} />
    </a>
  );
}
